[build]
  base = "web/"
  publish = "dist"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.92.0"

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL yarn build"

[context.branch-deploy]
  command = "URL=$DEPLOY_PRIME_URL yarn build"
