[build]
  base = "web/"
  publish = "dist"
  command = "yarn build"

[build.environment]
  HUGO_VERSION = "0.121.1"

[context.deploy-preview]
  command = "URL=$DEPLOY_PRIME_URL yarn build"

[context.branch-deploy]
  command = "URL=$DEPLOY_PRIME_URL yarn build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200