baseURL = "https://lower-off.phills.me.uk/api/"
languageCode = "en-gb"
title = "Lower-off Scenarios"
theme = ["api"]

[taxonomies]
  tag = "tags"

[outputs]
  page = ["json"]
  section = ["json"]
  home = ["json"]
  taxonomy = ["json"]
  term = ["json"]