name: Fixes
on:
  push:
    branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/cache@v2.1.5
        id: yarn-cache
        with:
          path: web/node_modules
          key: ${{ runner.os }}-web--node_modules-${{ hashFiles('web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-web--node_modules-

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm--home-${{ hashFiles('**/elm.json', 'web/elm-tooling.json') }}
          restore-keys: |
            ${{ runner.os }}-elm--home-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: yarn install --frozen-lockfile

      - name: Install elm tooling
        run: npx --no-install elm-tooling install

      - name: Run elm-format
        run: npx --no-install elm-format --yes

      - name: Apply elm-review fixes
        id: elm-review
        run: npx --no-install elm-review --fix-all-without-prompt
        continue-on-error: true

      - uses: peter-evans/create-pull-request@v3.9.1
        with:
          commit-message: 'Apply elm-review fixes'
          branch: fixes/${{ steps.extract_branch.outputs.branch }}
          title: "Apply elm-review fixes"
          body: "*This is an automated pull request because elm-review found problems that could be fixed automatically.*"
          reviewers: sparksp
          assignees: sparksp

  api-md5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Update api.md5
        run: git ls-files -s api/ | md5sum > web/api.md5

      - uses: peter-evans/create-pull-request@v3.9.1
        with:
          commit-message: "Update api.md5"
          branch: fixes/${{ steps.extract_branch.outputs.branch }}
          title: "Update api.md5"
          body: "This is an automated pull request because `api.md5` is out-of-date."
          reviewers: sparksp
          assignees: sparksp