name: Tests
on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.5
        id: yarn-cache
        with:
          path: web/node_modules
          key: ${{ runner.os }}-web--node_modules-${{ hashFiles('web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-web--node_modules-

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm--home-${{ hashFiles('**/elm.json', 'web/elm-tooling.json') }}
          restore-keys: |
            ${{ runner.os }}-elm--home-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: yarn install --frozen-lockfile

      - name: Install elm tooling
        run: npx --no-install elm-tooling install

      - name: Run elm-review
        run: npx --no-install elm-review

      - name: Run elm-format
        run: npx --no-install elm-format --validate
